### ISSUE TITLE
Publish to Terraform registry ?

### ISSUE THREAD

**Issue by Skyfallz** [hanneshayashi/terraform-provider-gdrive#2]
Hi,

this provider seems interesting, and is the only one available to handle Google Drives. Do you intent to publish it to Terraform Registry ?

Thanks,

**Comment by hanneshayashi** [comment]
I have not considered it yet to be honest, but if there is interest, I would be happy to.
The provider hasn't really been battle-tested in production yet. If you could provide me some feedback that would give me a better idea of it's maturity and what I still need to work on.

**Comment by Skyfallz** [comment]
I intend to test it along with the DeviaVir/gsuite provider, the goal would be to setup shared drives attached to team's groups. I will provide feedbacks if have some.

**Comment by hanneshayashi** [comment]
The provider is now available on the official Terraform Registry: https://registry.terraform.io/providers/hanneshayashi/gdrive/latest.
I have updated the README and example accordingly. Please let me know if it works for you.

**Comment by Skyfallz** [comment]
Works fine, thanks !
