### ISSUE TITLE
cannot upload csv as a spreadsheet

### ISSUE THREAD

**Issue by okaisti** [hanneshayashi/terraform-provider-gdrive#9]
a csv cant be uploaded as a spreadheet to drive e.g. 

```
resource "gdrive_file" "sheet_example" {
  mime_type = "application/vnd.google-apps.spreadsheet"
  name      = "test"
  parent    = gdrive_file.folder.id
  content   = "example.csv"
}
```
^ will not work.

The solution (via the API) is to set the filetype
```
  
const fileMetadata = {
    'title': 'My Report',
    'mimeType': 'application/vnd.google-apps.spreadsheet',
  };
  const media = {
    mimeType: 'text/csv', // THIS ONE
    body: fs.createReadStream('files/report.csv'),
  };
```

link to working example api call:
https://developers.google.com/drive/api/guides/manage-uploads#import_to_google_docs_types

so the module needs to expose setting (or autodetect) the filetype and add it to the api-call

**Comment by hanneshayashi** [comment]
Thanks for the report!

Yes, this seem like something I could add and I will take a look. It may take a little while though as I don't have much time to work on the provider right now. Maybe in a few weeks.

**Comment by okaisti** [comment]
awesome! otherwise the module fits our needs pretty well, so it would be much appreciated

**Comment by hanneshayashi** [comment]
I just released a new version of the provider that adds this capability. You should be able to upload a CSV file by specifying `mime_type_source = "text/csv"` in the file resource like so:

```terraform
# Updload a CSV file and import it as a Google Sheet
resource "gdrive_file" "import_csv" {
  name             = "my_sheet"
  mime_type        = "application/vnd.google-apps.spreadsheet"
  mime_type_source = "text/csv"
  content          = "./test.csv"
  parent           = gdrive_file.folder.id
}
```
Keep in mind that there is no comparison of contents. You can upload a new version by changing the `content` property of the file resource. This will keep the fileId of the Sheet stable but overwrite the content with the new version.

**Comment by hanneshayashi** [comment]
@kaisti-sitedrive have you had a chance to try the new version and see if it works for you? If it works, please feel free to close the issue.

**Comment by okaisti** [comment]
thanks! works like it should!
